MvcKutuphane/Controllers/DuyuruController.cs
using MvcKutuphane.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcKutuphane.Controllers
{
    public class DuyuruController : Controller
    {
        MvcKutuphaneYonetimSistemiEntities db = new MvcKutuphaneYonetimSistemiEntities();

        public ActionResult Index()
        {
            var values = db.Duyurular.ToList();
            return View(values);
        }

        [HttpGet]
        public ActionResult DuyuruEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DuyuruEkle(Duyurular duyurular)
        {
            db.Duyurular.Add(duyurular);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DuyuruDetay(int id)
        {
            var result = db.Duyurular.Find(id);

            return View(result);
        }

        public ActionResult DuyuruSil(int id)
        {
            var duyurular = db.Duyurular.Find(id);
            db.Duyurular.Remove(duyurular);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

       
        public ActionResult DuyuruGuncelle(Duyurular duyurular)
        {
            var result = db.Duyurular.Find(duyurular.DuyuruID);
            result.Tarih = duyurular.Tarih;
            result.Kategori = duyurular.Kategori;
            result.Icerik = duyurular.Icerik;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphane/Views/Duyuru/DuyuruDetay.cshtml
@model MvcKutuphane.Models.Entities.Duyurular
@{
    ViewBag.Title = "DuyuruDetay";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Duyuru Detay</h2>

@using (Html.BeginForm("DuyuruGuncelle", "Duyuru", FormMethod.Post))
{
    <div style="margin-bottom:15px;"></div>
    <div class="form-group">

        @Html.HiddenFor(x => x.DuyuruID)

        @Html.Label("Duyuru Kategorisi")
        @Html.TextBoxFor(x => x.Kategori, new { @Class = "form-control" })
        <br />

        @Html.Label("Duyuru İçeriği")
        @Html.TextAreaFor(x => x.Icerik, 5, 3, new { @Class = "form-control" })
        <br />

        @Html.Label("Duyuru Tarihi")
        @Html.TextBoxFor(x => x.Tarih, new { @Class = "form-control" })
        <br />
    </div>
    <div>
        <button class="btn btn-success"> Kaydet </button>
    </div>
}

MvcKutuphane/Views/Duyuru/DuyuruEkle.cshtml
@model MvcKutuphane.Models.Entities.Duyurular
@{
    ViewBag.Title = "DuyuruEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Yeni Duyuru Ekle</h2>

<form class="form-group" method="post">
    <div></div>
    <div style="margin-top:15px;">
        <label>Duyuru Kategorisi</label>
        @Html.TextBoxFor(x => x.Kategori, new { @Class = "form-control" })
    </div>
    <div style="margin-top:15px;">
        <label>Duyuru İçeriği</label>
        @Html.TextBoxFor(x => x.Icerik, new { @Class = "form-control" })
    </div>
    <div style="margin-top:15px;">
        <label>Duyuru Tarihi</label>
        @Html.TextBoxFor(x => x.Tarih, new { @Class = "form-control" })
    </div>
    <div style="margin-top:15px;">
        <button class="btn btn-info"> Duyuru Ekle </button>
    </div>
</form>

MvcKutuphane/Views/Duyuru/Index.cshtml
@model List<MvcKutuphane.Models.Entities.Duyurular>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
    int count = 0;

    string renk = "";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootsrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

<h2>Duyurular</h2>


<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kategori</th>
        <th>Tarih</th>
        <th>Sil</th>
        <th>İçerik</th>
    </tr>
    @foreach (var item in Model)
    {
        if (item.Kategori == "Diğer")
        {
            renk = "bg-info text-white";
        }
        if (item.Kategori == "Diğer Duyurular")
        {
            renk = "bg-info text-white";
        }
        if (item.Kategori == "Diger")
        {
            renk = "bg-info text-white";
        }
        if (item.Kategori == "Yeni Kitap")
        {
            renk = "bg-warning text-white";
        }
        if (item.Kategori == "İletişim")
        {
            renk = "bg-success text-white";
        }
        if (item.Kategori == "Kitapları Geciktirmeyin")
        {
            renk = "bg-danger text-white";
        }

        count++;
        <tr class="@renk">
            <td>@count</td>
            <td>@item.Kategori</td>
            <td>@(((DateTime)item.Tarih).ToString("dd-MM-yyyy"))</td>
            <td><a href="/Duyuru/DuyuruSil/@item.DuyuruID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Duyuru/DuyuruDetay/@item.DuyuruID" class="btn btn-default" style="background-color: skyblue; color: white;">Detaylar</a></td>
        </tr>
    }

</table>

<a class="btn btn-primary" href="/Duyuru/DuyuruEkle">Yeni Duyuru Ekle</a>