MvcKutuphane/Models/Entities/Mesajlar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajlar
    {
        public int MesajID { get; set; }
        public string Gonderen { get; set; }
        public string Alici { get; set; }
        public string Konu { get; set; }
        public string Icerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}

MvcKutuphane/Controllers/MesajlarController.cs
using MvcKutuphane.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcKutuphane.Controllers
{
    public class MesajlarController : Controller
    {
        MvcKutuphaneYonetimSistemiEntities db = new MvcKutuphaneYonetimSistemiEntities();    

        public ActionResult Index()
        {
            var memberMail = (string)Session["EMail"].ToString();
            var values = db.Mesajlar.Where(x => x.Alici == memberMail.ToString()).ToList();
            return View(values);
        }

        [HttpGet]
        public ActionResult YeniMesaj()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniMesaj(Mesajlar mesajlar)
        {
            var memberMail = (string)Session["EMail"].ToString();
            mesajlar.Gonderen = memberMail;
            mesajlar.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            db.Mesajlar.Add(mesajlar);
            db.SaveChanges();
            return RedirectToAction("GidenMesaj");
        }

        public ActionResult GidenMesaj()
        {
            var memberMail = (string)Session["EMail"].ToString();
            var values = db.Mesajlar.Where(x => x.Gonderen == memberMail.ToString()).ToList();
            return View(values);
        }

        public PartialViewResult Partial1()
        {
            var memberMail = (string)Session["EMail"].ToString();
            var gelenSayisi = db.Mesajlar.Where(x => x.Alici == memberMail).Count();
            ViewBag.gelenSayisi = gelenSayisi;
            var gidenSayisi = db.Mesajlar.Where(x => x.Gonderen == memberMail).Count();
            ViewBag.gidenSayisi = gidenSayisi;
            return PartialView();
        }
    }
}

MvcKutuphane/Views/Mesajlar/GidenMesaj.cshtml
@model List<MvcKutuphane.Models.Entities.Mesajlar>
@{
    ViewBag.Title = "GidenMesaj";
    Layout = "~/Views/Shared/_LayoutPanel.cshtml";
}

<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>AdminLTE 3 | Mailbox</title>

    <!-- Tell the browser to be responsive to screen width -->

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">

    <!-- Ionicons -->

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- icheck bootstrap -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/icheck-bootstrap/icheck-bootstrap.min.css">

    <!-- Theme style -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">

    <!-- Google Font: Source Sans Pro -->

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>

<body class="hold-transition sidebar-mini">

    <!-- Main Sidebar Container -->
    <!-- Main content -->

    <section class="content">

        <div class="row">

            @Html.Action("Partial1", "Mesajlar")

            <!-- /.col -->

            <div class="col-md-9">

                <div class="card card-primary card-outline">

                    <div class="card-header">

                        <h3 class="card-title">Giden Kutusu</h3>

                        <div class="card-tools">

                            <div class="input-group input-group-sm">

                                <input type="text" class="form-control" placeholder="E-Posta Ara">

                                <div class="input-group-append">

                                    <div class="btn btn-primary">

                                        <i class="fas fa-search"></i>

                                    </div>

                                </div>

                            </div>

                        </div>

                        <!-- /.card-tools -->

                    </div>

                    <!-- /.card-header -->

                    <div class="card-body p-0">

                        <div class="mailbox-controls">

                            <!-- Check all button -->

                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">

                                <i class="far fa-square"></i>

                            </button>

                            <div class="btn-group">

                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>

                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>

                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>

                            </div>

                            <!-- /.btn-group -->

                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>

                            <div class="float-right">

                                1-50/200

                                <div class="btn-group">

                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>

                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>

                                </div>

                                <!-- /.btn-group -->

                            </div>

                            <!-- /.float-right -->

                        </div>

                        <div class="table-responsive mailbox-messages">

                            <table class="table table-hover table-striped">

                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>

                                            <td>

                                                <div class="icheck-primary">

                                                    <input type="checkbox" value="" id="check1">

                                                    <label for="check1"></label>

                                                </div>

                                            </td>

                                            <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a></td>

                                            <td class="mailbox-name"><a href="read-mail.html">@item.Alici</a></td>

                                            <td class="mailbox-subject">

                                                <b>@item.Konu</b>

                                            </td>

                                            <td class="mailbox-attachment"></td>

                                            <td class="mailbox-date">@(((DateTime)item.Tarih).ToString("dd-MMM-yyyy"))</td>

                                        </tr>
                                    }

                                </tbody>

                            </table>

                            <!-- /.table -->

                        </div>

                        <!-- /.mail-box-messages -->

                    </div>

                    <!-- /.card-body -->

                    <div class="card-footer p-0">

                        <div class="mailbox-controls">

                            <!-- Check all button -->

                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">

                                <i class="far fa-square"></i>

                            </button>

                            <div class="btn-group">

                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>

                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>

                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>

                            </div>

                            <!-- /.btn-group -->

                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>

                            <div class="float-right">

                                1-50/200

                                <div class="btn-group">

                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>

                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>

                                </div>

                                <!-- /.btn-group -->

                            </div>

                            <!-- /.float-right -->

                        </div>

                    </div>

                </div>

                <!-- /.card -->

            </div>

            <!-- /.col -->

        </div>

        <!-- /.row -->

    </section>

    <!-- ./wrapper -->
    <!-- jQuery -->

    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->

    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>

    <!-- Page Script -->

    <script>
        $(function () {

            //Enable check and uncheck all functionality

            $('.checkbox-toggle').click(function () {

                var clicks = $(this).data('clicks')

                if (clicks) {

                    //Uncheck all checkboxes

                    $('.mailbox-messages input[type=\'checkbox\']').prop('checked', false)

                    $('.checkbox-toggle .far.fa-check-square').removeClass('fa-check-square').addClass('fa-square')

                } else {

                    //Check all checkboxes

                    $('.mailbox-messages input[type=\'checkbox\']').prop('checked', true)

                    $('.checkbox-toggle .far.fa-square').removeClass('fa-square').addClass('fa-check-square')

                }

                $(this).data('clicks', !clicks)

            })



            //Handle starring for glyphicon and font awesome

            $('.mailbox-star').click(function (e) {

                e.preventDefault()

                //detect type

                var $this = $(this).find('a > i')

                var glyph = $this.hasClass('glyphicon')

                var fa = $this.hasClass('fa')



                //Switch states

                if (glyph) {

                    $this.toggleClass('glyphicon-star')

                    $this.toggleClass('glyphicon-star-empty')

                }



                if (fa) {

                    $this.toggleClass('fa-star')

                    $this.toggleClass('fa-star-o')

                }

            })

        })</script>

    <!-- AdminLTE for demo purposes -->

    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>

</body>

</html>

MvcKutuphane/Views/Mesajlar/Index.cshtml
@model List<MvcKutuphane.Models.Entities.Mesajlar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPanel.cshtml";
}

<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>AdminLTE 3 | Mailbox</title>

    <!-- Tell the browser to be responsive to screen width -->

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">

    <!-- Ionicons -->

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- icheck bootstrap -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/icheck-bootstrap/icheck-bootstrap.min.css">

    <!-- Theme style -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">

    <!-- Google Font: Source Sans Pro -->

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>

<body class="hold-transition sidebar-mini">

    <!-- Main Sidebar Container -->
    <!-- Main content -->

    <section class="content">

        <div class="row">

            @Html.Action("Partial1", "Mesajlar")

            <!-- /.col -->

            <div class="col-md-9">

                <div class="card card-primary card-outline">

                    <div class="card-header">

                        <h3 class="card-title">Gelen Kutusu</h3>

                        <div class="card-tools">

                            <div class="input-group input-group-sm">

                                <input type="text" class="form-control" placeholder="E-Posta Ara">

                                <div class="input-group-append">

                                    <div class="btn btn-primary">

                                        <i class="fas fa-search"></i>

                                    </div>

                                </div>

                            </div>

                        </div>

                        <!-- /.card-tools -->

                    </div>

                    <!-- /.card-header -->

                    <div class="card-body p-0">

                        <div class="mailbox-controls">

                            <!-- Check all button -->

                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">

                                <i class="far fa-square"></i>

                            </button>

                            <div class="btn-group">

                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>

                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>

                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>

                            </div>

                            <!-- /.btn-group -->

                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>

                            <div class="float-right">

                                1-50/200

                                <div class="btn-group">

                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>

                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>

                                </div>

                                <!-- /.btn-group -->

                            </div>

                            <!-- /.float-right -->

                        </div>

                        <div class="table-responsive mailbox-messages">

                            <table class="table table-hover table-striped">

                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>

                                            <td>

                                                <div class="icheck-primary">

                                                    <input type="checkbox" value="" id="check1">

                                                    <label for="check1"></label>

                                                </div>

                                            </td>

                                            <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a></td>

                                            <td class="mailbox-name"><a href="read-mail.html">@item.Gonderen</a></td>

                                            <td class="mailbox-subject">

                                                <b>@item.Konu</b>

                                            </td>

                                            <td class="mailbox-attachment"></td>

                                            <td class="mailbox-date">@(((DateTime)item.Tarih).ToString("dd-MMM-yyyy"))</td>

                                        </tr>
                                    }

                                </tbody>

                            </table>

                            <!-- /.table -->

                        </div>

                        <!-- /.mail-box-messages -->

                    </div>

                    <!-- /.card-body -->

                    <div class="card-footer p-0">

                        <div class="mailbox-controls">

                            <!-- Check all button -->

                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">

                                <i class="far fa-square"></i>

                            </button>

                            <div class="btn-group">

                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>

                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>

                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>

                            </div>

                            <!-- /.btn-group -->

                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>

                            <div class="float-right">

                                1-50/200

                                <div class="btn-group">

                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>

                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>

                                </div>

                                <!-- /.btn-group -->

                            </div>

                            <!-- /.float-right -->

                        </div>

                    </div>

                </div>

                <!-- /.card -->

            </div>

            <!-- /.col -->

        </div>

        <!-- /.row -->

    </section>

    <!-- ./wrapper -->
    <!-- jQuery -->

    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->

    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>

    <!-- Page Script -->

    <script>
        $(function () {

            //Enable check and uncheck all functionality

            $('.checkbox-toggle').click(function () {

                var clicks = $(this).data('clicks')

                if (clicks) {

                    //Uncheck all checkboxes

                    $('.mailbox-messages input[type=\'checkbox\']').prop('checked', false)

                    $('.checkbox-toggle .far.fa-check-square').removeClass('fa-check-square').addClass('fa-square')

                } else {

                    //Check all checkboxes

                    $('.mailbox-messages input[type=\'checkbox\']').prop('checked', true)

                    $('.checkbox-toggle .far.fa-square').removeClass('fa-square').addClass('fa-check-square')

                }

                $(this).data('clicks', !clicks)

            })



            //Handle starring for glyphicon and font awesome

            $('.mailbox-star').click(function (e) {

                e.preventDefault()

                //detect type

                var $this = $(this).find('a > i')

                var glyph = $this.hasClass('glyphicon')

                var fa = $this.hasClass('fa')



                //Switch states

                if (glyph) {

                    $this.toggleClass('glyphicon-star')

                    $this.toggleClass('glyphicon-star-empty')

                }



                if (fa) {

                    $this.toggleClass('fa-star')

                    $this.toggleClass('fa-star-o')

                }

            })

        })</script>

    <!-- AdminLTE for demo purposes -->

    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>

</body>

</html>

MvcKutuphane/Views/Mesajlar/Partial1.cshtml
<div class="col-md-3">

    <a href="/Mesajlar/YeniMesaj" class="btn btn-primary btn-block mb-3">Yeni Mesaj</a>

    <div class="card">

        <div class="card-header">

            <h3 class="card-title">Seçenekler</h3>

            <div class="card-tools">

                <button type="button" class="btn btn-tool" data-card-widget="collapse">

                    <i class="fas fa-minus"></i>

                </button>

            </div>

        </div>

        <div class="card-body p-0">

            <ul class="nav nav-pills flex-column">

                <li class="nav-item active">

                    <a href="/Mesajlar/Index" class="nav-link">
                        <i class="fas fa-inbox"></i> Gelen Kutusu
                        <span class="badge bg-primary float-right">@ViewBag.gelenSayisi</span>
                    </a>
                </li>

                <li class="nav-item">

                    <a href="/Mesajlar/GidenMesaj" class="nav-link">
                        <i class="far fa-envelope"></i> Giden Kutusu
                        <span class="badge bg-danger float-right">@ViewBag.gidenSayisi</span>
                    </a>
                </li>

                <li class="nav-item">

                    <a href="#" class="nav-link">
                        <i class="far fa-file-alt"></i> Taslaklar
                        <span class="badge bg-success float-right">0</span>
                    </a>

                </li>

                <li class="nav-item">

                    <a href="#" class="nav-link">

                        <i class="fas fa-filter"></i> Spam

                        <span class="badge bg-warning float-right">0</span>
                    </a>

                </li>

                <li class="nav-item">

                    <a href="#" class="nav-link">

                        <i class="far fa-trash-alt"></i> Çöp Kutusu
                        <span class="badge bg-gray-dark float-right">0</span>
                    </a>

                </li>

            </ul>

        </div>

        <!-- /.card-body -->

    </div>

    <!-- /.card -->

    <div class="card">

        <div class="card-header">

            <h3 class="card-title">Etiketler</h3>

            <div class="card-tools">

                <button type="button" class="btn btn-tool" data-card-widget="collapse">

                    <i class="fas fa-minus"></i>

                </button>

            </div>

        </div>

        <div class="card-body p-0">

            <ul class="nav nav-pills flex-column">

                <li class="nav-item">

                    <a href="#" class="nav-link">

                        <i class="far fa-circle text-danger"></i>

                        Önemli

                    </a>

                </li>

                <li class="nav-item">

                    <a href="#" class="nav-link">

                        <i class="far fa-circle text-warning"></i> Tanıtımlar

                    </a>

                </li>

                <li class="nav-item">

                    <a href="#" class="nav-link">

                        <i class="far fa-circle text-primary"></i>

                        Sosyal Medya

                    </a>

                </li>

            </ul>

        </div>

        <!-- /.card-body -->

    </div>

    <!-- /.card -->

</div>

MvcKutuphane/Views/Mesajlar/YeniMesaj.cshtml
@model MvcKutuphane.Models.Entities.Mesajlar
@{
    ViewBag.Title = "YeniMesaj";
    Layout = "~/Views/Shared/_LayoutPanel.cshtml";
}


<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>AdminLTE 3 | Compose Message</title>

    <!-- Tell the browser to be responsive to screen width -->

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->

    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">

    <!-- Ionicons -->

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- Theme style -->

    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">

    <!-- summernote -->

    <link rel="stylesheet" href="../../plugins/summernote/summernote-bs4.css">

    <!-- Google Font: Source Sans Pro -->

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>

<body class="hold-transition sidebar-mini">

    <!-- Navbar -->
    <!-- Main content -->

    <section class="content">

        <div class="container-fluid">

            <div class="row">

                @Html.Action("Partial1", "Mesajlar")

                <!-- /.col -->

                <div class="col-md-9">

                    <div class="card card-primary card-outline">

                        <div class="card-header">

                            <h3 class="card-title">Yeni Mesaj Oluştur</h3>

                        </div>

                        <!-- /.card-header -->
                        <form class="form-group" method="post">
                            <div class="card-body">

                                <div class="form-group">

                                    <input class="form-control" name="Alici" placeholder="Kime:">

                                </div>

                                <div class="form-group">

                                    <input class="form-control" name="Konu" placeholder="Konu:">

                                </div>

                                <div class="form-group">

                                    <textarea id="compose-textarea" name="Icerik" class="form-control" style="height: 300px"> </textarea>

                                </div>

                            </div>

                            <div class="card-footer">

                                <div class="float-right">
                                    <button type="submit" class="btn btn-primary"><i class="far fa-envelope"></i> Gönder</button>

                                </div>

                            </div>
                        </form>
                    </div>

                    <!-- /.card -->

                </div>

                <!-- /.col -->

            </div>

            <!-- /.row -->

        </div><!-- /.container-fluid -->

    </section>

    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->

    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->

    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>

    <!-- AdminLTE for demo purposes -->

    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>

    <!-- Summernote -->

    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>

    <!-- Page Script -->

    <script>
        $(function () {

            //Add text editor

            $('#compose-textarea').summernote()

        })</script>

</body>

</html>