MvcKutuphane/Controllers/AdminLoginController.cs
using MvcKutuphane.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MvcKutuphane.Controllers
{
    [AllowAnonymous]
    public class AdminLoginController : Controller
    {

        MvcKutuphaneYonetimSistemiEntities db = new MvcKutuphaneYonetimSistemiEntities();

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Admin admin)
        {
            var values = db.Admin.FirstOrDefault(x => x.Kullanici == admin.Kullanici && x.Sifre == admin.Sifre);
            if (values != null)
            {
                FormsAuthentication.SetAuthCookie(values.Kullanici, false);
                Session["Kullanici"] = values.Kullanici.ToString();
                return RedirectToAction("Index", "Kategori");
            }
            else
            {
                return View();
            }
        }

    }
}

MvcKutuphane/Controllers/LoginController.cs
using MvcKutuphane.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MvcKutuphane.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        MvcKutuphaneYonetimSistemiEntities db = new MvcKutuphaneYonetimSistemiEntities();

        [HttpGet]
        public ActionResult GirisYap()
        {
            return View();
        }

        public ActionResult GirisYap(Uyeler uyeler)
        {
            var values = db.Uyeler.FirstOrDefault(x => x.EMail == uyeler.EMail && x.Sifre == uyeler.Sifre);
            if (values != null)
            {
                FormsAuthentication.SetAuthCookie(values.EMail, false);
                Session["Email"] = values.EMail.ToString();
                //TempData["UyeID"] = values.UyeID.ToString();
                //TempData["UyeAd"] = values.UyeAd.ToString();
                //TempData["UyeSoyad"] = values.UyeSoyad.ToString();
                //TempData["KullaniciAd"] = values.KullaniciAd.ToString();
                //TempData["Sifre"] = values.Sifre.ToString();
                //TempData["UyeOkul"] = values.UyeOkul.ToString();
                return RedirectToAction("Index", "Panelim");
            }
            else
            {
                return View();
            }
        }
    }
}

MvcKutuphane/Views/AdminLogin/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="~/AdminLTE-3.0.4/index2.html"><b>Admin</b> Giriş</a>
        </div>
        <!-- /.login-logo -->

        @using (Html.BeginForm("Login", "AdminLogin", FormMethod.Post))
        {
            <div class="card">
                <div class="card-body login-card-body">
                    <p class="login-box-msg">Oturum Aç</p>

                    <form action="~/AdminLTE-3.0.4/index3.html" method="post">
                        <div class="input-group mb-3">
                            <input type="email" name="Kullanici" class="form-control" placeholder="Kullanıcı E-Posta">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <input type="password" name="Sifre" class="form-control" placeholder="Şifre">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-8">
                                <div class="icheck-primary">
                                    <input type="checkbox" id="remember">
                                    <label for="remember">
                                        Beni Hatırla
                                    </label>
                                </div>
                            </div>
                            <!-- /.col -->
                            <div class="col-4">
                                <button type="submit" class="btn btn-primary btn-block">Giriş</button>
                            </div>
                            <!-- /.col -->
                        </div>
                    </form>

                    <div class="social-auth-links text-center mb-3">
                        <p>- Veya -</p>
                        <a href="#" class="btn btn-block btn-primary">
                            <i class="fab fa-facebook mr-2"></i> Facebook ile Bağlan
                        </a>
                        <a href="#" class="btn btn-block btn-danger">
                            <i class="fab fa-google-plus mr-2"></i> Google ile Bağlan
                        </a>
                    </div>
                    <!-- /.social-auth-links -->

                    <p class="mb-1">
                        <a href="forgot-password.html">Şifremi Unuttum</a>
                    </p>
                    <p class="mb-0">
                        <a href="register.html" class="text-center">Vitrine Geri Dön</a>
                    </p>
                </div>
                <!-- /.login-card-body -->
            </div>
        }
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>

</body>
</html>