MvcKutuphane/Controllers/GrafikController.cs
using MvcKutuphane.Models;
using MvcKutuphane.Models.Siniflarim;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcKutuphane.Controllers
{
    public class GrafikController : Controller
    {
        
      

        public ActionResult Index()
        {

            return View();
        }

        public ActionResult VisualizeKitapResult()
        {
            return Json(Liste());
        }

        public List<Class2> Liste()
        {
            List<Class2> cs = new List<Class2>();
            cs.Add(new Class2() {
                Yayinevi = "Güneş",
                Sayi = 7
            });
            cs.Add(new Class2() {
                Yayinevi = "Mars",
                Sayi = 4
            });
            cs.Add(new Class2() {
                Yayinevi = "Jüpiter",
                Sayi = 6
            });
            return cs;
        }
    }
}

MvcKutuphane/Views/Grafik/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeKitapResult", "Grafik")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.Yayinevi, obj.Sayi]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Kitap - Yayınevi Grafiği",
                width: 1000,
                height: 800,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>